name: CTest
on:
  push:
jobs:
  run-ctest:
    name: Run CTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: threeal/cmake-action@v2.1.0
      
      - name: Test
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Debug
